### ISSUE TITLE
ReturnUrl not working

### ISSUE THREAD

**Issue by eziel** [chsakell/aspnet5-angular2-typescript#15]
When clicking on albums I see in the console the following error:
http://localhost:5000/Account/Login?ReturnUrl=%2Fapi%2Falbums%2F0%2F3

**Comment by chsakell** [comment]
The framework redirects you to the default Login page due to the _CookieAuthenticationOptions_ we used in the _Startup_ class. 

``` csharp
app.UseCookieAuthentication(new CookieAuthenticationOptions
{
     AutomaticAuthenticate = true,
     AutomaticChallenge = true
 });
```

In case you run the app under _IIS_ you can just change it to:

``` csharp
app.UseCookieAuthentication(new CookieAuthenticationOptions
{
     AutomaticAuthenticate = true,
     AutomaticChallenge = false
 });
```

.. which is what we used to have before RC2 and you will not get the error. After migrating though, the _**AutomaticChallenge = false**_ doesn't work well outside IIS (_aka. dotnet run_).
Till we fix this and work well for both _IIS_ and _Kestrel_, I have temporary used a **404 not found** handler when making requests that require authorization.

``` typescript
getAlbums(): void {
        this.albumsService.get(this._page)
            .subscribe(res => {               
                var data:any = res.json();
                this._albums = data.Items;
                this._page = data.Page;
                this._pagesCount = data.TotalPages;
                this._totalCount = data.TotalCount;
            },
            error => {

                if (error.status == 401 || error.status == 404) {
                    this.notificationService.printErrorMessage('Authentication required');
                    this.utilityService.navigateToSignIn();
                }
            });
    }
```

**Comment by eziel** [comment]
Thank you for the information. 

BTW I really want to change the identity to use default asp.net Identity. do you have some sample on that? (in the blog comments you wrote that you have in plan to make it..)

**Comment by eziel** [comment]
No more error when using IIS, but its not being redirected to the albums page after login.. its redirected to the home page.

**Comment by chsakell** [comment]
You need to use _Github_ and _open-source_ properly. The issue you have opened has been explained and will be closed when fixed. All others are irrelevant and certainly not bugs.
